### ISSUE TITLE
Error with Eureka Pen Spinning Demo 

### ISSUE THREAD

**Issue by comwitch** [eureka-research/Eureka#21]
hello, I want to test the Eureka with given environment, when I test the traind Pen spinning in Eureka but there is some Error

`JointSpec type free not yet supported!
JointSpec type free not yet supported!
JointSpec type free not yet supported!
[Error] [carb.gym.plugin] *** Could not create contact graph to compute collision filters! Are contacts specified properly?

JointSpec type free not yet supported!
JointSpec type free not yet supported!
[Error] [carb.gym.plugin] *** Could not create contact graph to compute collision filters! Are contacts specified properly?

{'observation_space': Box(-inf, inf, (211,), float32), 'action_space': Box(-1.0, 1.0, (20,), float32), 'agents': 1, 'value_size': 1}
build mlp: 211
RunningMeanStd:  (1,)
RunningMeanStd:  (211,)
=> loading checkpoint '/home/tuna831/eureka/isaacgymenvs/isaacgymenvs/checkpoints/EurekaPenSpinning.pth'
세그멘테이션 오류 (코어 덤프됨)`

I tested other task environment like humanoid but that is good working.

how can I solve this error

**Comment by fantasy4everts** [comment]
same problem   there is no solution on internet.  Chatgpt cannot give answer either.

**Comment by Yyin-Tta** [comment]
In isaacgymenvs/isaacgymenvs/cfg/task/ShadowHandSpin.yaml, modify the parameter numEnvs to resolve_ Default: 1
The reason may be that the original parameters are too large, resulting in a complex environment

**Comment by likw99** [comment]
Met similar issue, fixed with Yyin-Tta's suggestion.

**Comment by comwitch** [comment]
Thank you!
