### ISSUE TITLE
-

### ISSUE THREAD

**Issue by NextMyLove** [eureka-research/Eureka#30]

**Comment by NextMyLove** [comment]
![Uploading QQ图片20231127111258.png…]()

**Comment by NextMyLove** [comment]
![image](https://github.com/eureka-research/Eureka/assets/87683918/926fc119-c758-4a58-94b1-a302780963f2)

**Comment by NextMyLove** [comment]
![image](https://github.com/eureka-research/Eureka/assets/87683918/054b0306-7814-4ad5-9652-00d18653aa76)

**Comment by zmj1818** [comment]
I met the same problem today.

**Comment by NextMyLove** [comment]
Why so many errors and not even one success?

**Comment by yuChen-XD** [comment]
I met the same problem. Do you solve it?  I tried GPT4 but the problem was not solved.
