### ISSUE TITLE
Error from Eureka Pen Spinning Demo

### ISSUE THREAD

**Issue by ramkumarkoppu** [eureka-research/Eureka#5]
Tried
**cd isaacgymenvs/isaacgymenvs**
**python train.py test=True headless=False force_render=True task=ShadowHandSpin checkpoint=checkpoints/EurekaPenSpinning.pth**
and I get

wHandSpin checkpoint=checkpoints/EurekaPenSpinning.pth
Importing module 'gym_38' (/home/ram/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/ram/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.0.0+cu117
Device count 1
/home/ram/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/ram/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Emitting ninja build file /home/ram/.cache/torch_extensions/py38_cu117/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2023-10-21 20:22:16,606 - INFO - logger - logger initialized
<unknown>:3: DeprecationWarning: invalid escape sequence \*
Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html
train.py:75: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_name="config", config_path="./cfg")
/home/ram/anaconda3/envs/eureka/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:415: UserWarning: In config: Invalid overriding of hydra/job_logging:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
Traceback (most recent call last):
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/jasonyma/isaac_gpt/train/2023-10-21_20-22-17'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/jasonyma/isaac_gpt/train'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/jasonyma/isaac_gpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/jasonyma'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  [Previous line repeated 1 more time]
  File "/home/ram/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/data2'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by JasonMa2016** [comment]
Fixed. Thank you for trying out our code and providing early feedback!

**Comment by AndreV84** [comment]
@JasonMa2016 
Nihao!

got into the same issue of data2 folder absence```

what was the fix you resolved it with? how to apply it?
Xie Xie
`ileNotFoundError: [Errno 2] No such file or directory: '/data2/jasonyma/isaac_gpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr/anaconda3/envs/eureka/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/jasonyma'
`
```
