### ISSUE TITLE
questions regarding use of Eureka for a real Robot

### ISSUE THREAD

**Issue by ramkumarkoppu** [eureka-research/Eureka#8]
Hi,

I have following questions regarding use of Eureka for a real Robot:
1. What files are the better place to add real Robot SDK calls to drive real robot?
2. Are there any plans to integrate on-device LLM like llama instead of cloud access of GPT-4 or 3.5 to have near Real time Robot control?
3. Optionally, are there any plans to add four legged Robot similar to Spot in the simulator?

**Comment by juliaabrams** [comment]
The best place to add real Robot SDK calls to drive a real Robot in Eureka depends on the specific SDK and the desired functionality. However, some common places include:

The RobotController class. This class provides a high-level interface for controlling a Robot, and it is a good place to add SDK calls for basic functionality such as moving the Robot around, manipulating objects, and collecting sensor data.
The RobotActuator and RobotSensor classes. These classes provide lower-level interfaces for controlling individual actuators and sensors on the Robot. They can be used to add SDK calls for more complex functionality, such as controlling the Robot's gripper or performing precise navigation.
The RobotWorld class. This class represents the Robot's world, and it can be used to add SDK calls for interacting with the environment, such as detecting obstacles or planning paths.
Integration with on-device LLM
There are currently no plans to integrate on-device LLMs such as LaMDA into Eureka. However, this is a possibility that the team is considering for the future.

Four-legged Robot in the simulator
There are also currently no plans to add a four-legged Robot similar to Spot to the Eureka simulator. However, this is something that the team is open to considering in the future.

In the meantime, there are a number of other Robot simulators available that support four-legged Robots, such as PyBullet and SimSpark. These simulators can be used to develop and test Robot control algorithms before deploying them to real Robots.
